services:
  dev:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

  staging:
    build:
      context: .
      target: production-runtime
      args:
        APP_ENV: staging
    ports:
      - "8081:80"

  production:
    build:
      context: .
      target: production-runtime
      args:
        APP_ENV: production
    ports:
      - "8080:80"